<a href="https://colab.research.google.com/github/henrykohl/DeepLearningByPytorchTutorial/blob/master/video_notebooks/00_PyTorch_Fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <font color="red">00. PyTorch Fundamentals</font>

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

<font color="red">原版本</font>


---


1.13.1+cu116

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
!nvidia-smi

Tue Mar  7 09:45:01 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0    27W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
"""純量tensor"""
scalar=torch.tensor(7)
scalar

tensor(7)

In [7]:
"""純量tensor的維度"""
scalar.ndim

0

In [3]:
# Get tensor back as Python int
"""從tensor中取出包含數據"""
scalar.item()

7

In [10]:
# 新增
scalar.shape

torch.Size([])

In [4]:
# Vector
"""向量tensor"""
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
"""向量tensor的維度"""
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
# MATRIX
"""矩陣tensor"""
MATRIX = torch.tensor([[7,8],
             [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
"""矩陣tensor的維度"""
MATRIX.ndim

2

In [ ]:
# MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
"""多維矩陣tensor"""
TENSOR = torch.tensor([[[1, 2, 3],
              [3, 6, 9],
              [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
"""多維矩陣tensor的維度"""
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensor

Why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3, 4)
"""隨機矩陣tensor"""
random_tensor = torch.rand(size=( 3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6758, 0.6224, 0.1871, 0.7829],
         [0.0741, 0.7050, 0.8841, 0.0732],
         [0.1809, 0.7319, 0.2564, 0.7588]]),
 torch.float32)

In [19]:
"""隨機矩陣tensor的維度"""
random_tensor.ndim

2

In [20]:
# Create a random tensor of size (224, 224, 3)
# random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [21]:
# torch.rand(size=(3,3))
torch.rand(3,3)

tensor([[0.5895, 0.2535, 0.7568],
        [0.5423, 0.6641, 0.5246],
        [0.9174, 0.3923, 0.0570]])

### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [25]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange(), torch.range() is deprecated 
"""建議不要使用此過時用法"""
# torch.range(0, 10) # Note: this may return an error in the future



```
torch.range(0, 10)
```


<ipython-input-35-199603dfd195>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10) # Note: this may return an error in the future
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
# Create a range of values 0 to 10
"""torch.arange完整用法"""
torch.arange(start=0, end=10, step=1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# User torch.arange()
"""torch.arange簡單用法"""
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Can also create a tensor of zeros similar to another tensor (Creating tensors like)
ten_zeros = torch.zeros_like(input=one_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [32]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                    dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                  dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                  dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                  device=None, # 設定可以是 `cuda` 或是 `cpu` 。defaults to None, which uses the default tensor type
                  requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

In [40]:
# 轉換tensor的type類型
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
# tensor [3., 6., 9.] x tensor [3., 6., 9.]
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [42]:
# int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor 

tensor([3, 6, 9])

In [43]:
float_16_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [44]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5283, 0.1761, 0.3159, 0.1116],
        [0.7492, 0.3822, 0.1793, 0.8054],
        [0.3143, 0.3607, 0.8929, 0.3811]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu



```
some_tensor.size, some_tensor.shape
```
(`<function Tensor.size>`, torch.Size([3, 4]))


In [45]:
some_tensor.size() # size 是function, 不是attribute

torch.Size([3, 4])

### Manipulating tensors (tensor operations)
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [46]:
# Create a tensor of values and add a number to it
tensor10 = torch.tensor([1, 2, 3])
tensor10 + 10

tensor([11, 12, 13])

In [47]:
# Multiply it by 10
tensor10 * 10

tensor([10, 20, 30])

In [48]:
# Tensors don't change unless reassigned
tensor10

tensor([1, 2, 3])

In [49]:
# Subtract
tensor10 - 10

tensor([-9, -8, -7])

In [50]:
# Can also use torch functions (Try out PyTorch in-built bunctions)
torch.multiply(tensor10, 10)

tensor([10, 20, 30])

In [51]:
torch.add(tensor10, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [52]:
# Element wise multiplication
print(tensor10, "*", tensor10)
print(f"Equals: {tensor10*tensor10}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [53]:
# Matrix multiplication
torch.matmul(tensor10, tensor10)

tensor(14)

In [55]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor10)):
  value += tensor10[i] * tensor10[i]
value

CPU times: user 1.22 ms, sys: 0 ns, total: 1.22 ms
Wall time: 1.08 ms


tensor(14)

In [56]:
%%time
torch.matmul(tensor10, tensor10)

CPU times: user 954 µs, sys: 0 ns, total: 954 µs
Wall time: 908 µs


tensor(14)

In [57]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor10 @ tensor10

tensor(14)

In [ ]:
"""錯誤示範, 原因:inner dimensions不正確"""
torch.matmul(torch.rand(3,2), torch.rand(3,2)) 

RuntimeError: ignored

In [ ]:
# torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.2746, 0.2376, 0.2146],
        [0.4496, 0.3912, 0.2910],
        [0.3501, 0.3017, 0.3033]])

### One of the most common errors in deep learning (shape errors)

In [58]:
# Shapes need to be in the right way  (Shapes for matrix multiplication) 
tensor_A = torch.tensor([[1, 2],
              [3, 4],
              [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
              [8, 11], 
              [9, 12]], dtype=torch.float32)

torch.mm(tensor_A, tensor_B) # (this will error) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: ignored

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a `transpose`

A **transpose** switches the axes or dimensions of a given tensor.

In [59]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [60]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [61]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [62]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output =  torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [63]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
"""取最小值的兩種方式"""
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
"""取最大值的兩種方式"""
torch.max(x), x.max()

(tensor(90), tensor(90))

In [64]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x)

RuntimeError: ignored

In [65]:
"""取平均的兩種方式"""
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [66]:
# Find the sum
"""取總和的兩種方式"""
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
# Find the positon in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [68]:
x[0]

tensor(0)

In [69]:
# Find the positon in tensor that has the minimum value with argmax()
x.argmax()

tensor(9)

In [70]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimenions from a tensor
* Unsqueeze - add a `1` dimension to at target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certian way

In [71]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7) # 會出錯
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [72]:
x_reshaped = x.reshape(1, 9) 
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
x_reshaped = x.reshape(9, 1) 
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [74]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [83]:
"""使用view, z 與 x 共用相同記憶體位置"""
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [77]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=0 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [78]:
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [79]:
# torch.squeeze() - removes all single dimensions form a target tensor
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [80]:
x_reshaped.shape

torch.Size([9, 1])

In [81]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [82]:
x_reshaped.squeeze().shape

torch.Size([9])

In [84]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [85]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [86]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}") # [colour_channels, height, width]
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [87]:
x_original[0,0,0]=728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [92]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [89]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")  #Let's index on our new tensor
print(f"Second square bracket: {x[0][0]}") # Let's index on the middle bracket (dim=1)
print(f"Third square bracket: {x[0][0][0]}") # Let's index on the most inner bracket (last dimension)

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [93]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [94]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [95]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
"""在此例,等於x[0, 1, 1]"""
x[:, 1, 1] 

tensor([5])

In [96]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
"""等於x[0, 0]"""
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [97]:
# Index on x to return 9
print(x[0][0][2])

# Index on x to return 3, 6, 9
print(x[:,:,2])

tensor(3)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [98]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specific otherwise
# tensor = torch.from_numpy(array,dtype=torch.float32) # 會出錯
# tensor = torch.from_numpy(array).type(torch.float32) # 有特別指定，是可以的
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [99]:
array.dtype

dtype('float64')

In [100]:
tensor.dtype

torch.float64

In [101]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [102]:
# Change the value of array, what will this do to `tensor`? 
"""答案：不變"""
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [103]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [104]:
numpy_tensor.dtype

dtype('float32')

In [105]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)
In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them of the dat -> again -> agina -> again ...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially when the random seed does is "flavour" the randomness.

In [106]:
torch.rand(3,3)

tensor([[0.3347, 0.6690, 0.3796],
        [0.1018, 0.0558, 0.8645],
        [0.4204, 0.8836, 0.2595]])

In [107]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1240, 0.6756, 0.2829, 0.9814],
        [0.2873, 0.7254, 0.4765, 0.4789],
        [0.6664, 0.3749, 0.5195, 0.4888]])

Tensor B:
tensor([[0.1316, 0.9048, 0.0560, 0.9942],
        [0.6934, 0.3164, 0.7022, 0.2342],
        [0.1236, 0.1264, 0.6083, 0.5141]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [108]:
# Let's make some random but reproducible tensors
import torch
import random

# Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # 還需要再設定一次 try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working bhind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - User Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, ther's lots of options..., see this post for option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computeers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [109]:
!nvidia-smi # 要先開啟GPU

Wed May 31 11:15:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [110]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#bestpractices

E.g. run on GPU if available, else default to CPU

In [111]:
# Steup device agnostic code (Set device type)

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [112]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [115]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3], device="cpu") # 等同 tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
"""使用 .device 可以檢查 數據所在裝置位置"""
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [116]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [117]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [118]:
# Instead, copy the tensor back to cpu 
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [119]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')



```
tensor_on_gpu.device
```
device(type='cuda', index=0)


### Exercises & Extra-curriculum
See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises